### PR TITLE
Add Docker Compose and required images

### PR DESCRIPTION
**Pull request by Celant**
Added the docker-compose.yml file and all the related images needed to
spin up a working version of the site, including memcached. Images use
the Laradock Docker images as upstreams

### CODE REVIEW

**Comment by Byorun** [comment]
I may be wrong,
I don't know docker but shouldn't this also "install" the application itself? (composer install, etc...)

**Comment by sorianog** [comment]
@Razzeee This would definitely help me. Memcached is one of the obstacles preventing me from running a local version of the site.

**Comment by beatsaver** [comment]
Memcache is like the easiest thing in the world to install, stop being lazy

**Comment by sorianog** [comment]
@beatsaver What OS did you install it on? Tried at least 2 times, 2 different methods on Windows with no success. Did not want to spend 2 hours to get it to run locally...

**Comment by beatsaver** [comment]
Ubuntu 1804 only I suggest if you have Windows 10 to install the Linux
subsystem for Windows or run it inside of a virtual machine

**Comment by Byorun** [comment]
For the record I am developing on windows subsystem linux with mysql and memcache installed on ubuntu 1804

**Comment by Celant** [comment]
Hey all. @Byorun I just re-read the commit, and I didn't forget. It seems automating the composer install wasn't particularly trivial, so as a stop-gap fix the readme contains the instructions on how to run composer install. I think automating that is slightly out of the scope of this PR, as it'll take some time to do. As far as I can see, this should be ready to merge. If @Razzeee or @sorianog want to test it too, that'd be useful.

**Comment by Razzeee** [comment]
I tried to run it yesterday and realized that docker requires windows pro...
Will have to figure something out for that, as running memcached doesn't seem practial on windows...

So I will have to try at work, but that's a different problem as I needed to disable Hpyer-V due to problems. So please don't wait for my approval before merging this.

**Comment by beatsaver** [comment]
you should just use a virtual machine or run the linux subsystem, as that
will run memcache just fine

**Comment by sorianog** [comment]
Hey all,

Just got myself a MacBook so I'll see if I have better luck with actually
standing up the site for testing! :)

**Comment by Razzeee** [comment]
After looking back at this and remembering the other stuff I did in laravel I think we should use homestead instead of docker.

https://laravel.com/docs/5.7/homestead#introduction

I would prepare a pr if we can agree on this.

**Comment by Byorun** [comment]
@Razzeee you can do that, but keep in mind that we are still using Laravel 5.6. So if there is something special regarding homestead and 5.7 it might not work with 5.6

**Comment by Celant** [comment]
Regardless of the use of Homestead or not, Docker can still be useful. Devs seem to prefer Docker more, and Docker can be used for production deployments too, unlike Homestead. Both would be good :)

**Comment by Razzeee** [comment]
yes, very useful for production build, but not sure if it's worth it if the person hosting the site is not using/planning to use docker to deploy.

**Comment by lolPants** [comment]
This isn't really helpful since Docker isn't being used in prod.

**Pull request closed without merging**
